export type AppRole = 'admin' | 'teacher' | 'user';

export type AppPermission =
  | 'students:read'
  | 'students:write'
  | 'attendance:read'
  | 'attendance:write'
  | 'auth:invite'
  | 'auth:manage-users'
  | 'classes:read'
  | 'classes:write'
  | 'events:read'
  | 'events:write'
  | 'ex-students:read'
  | 'ex-students:write'
  | 'parents:read'
  | 'parents:write'
  | 'pools:read'
  | 'pools:write'
  | 'results:read'
  | 'results:write'
  | 'teachers:read'
  | 'teachers:write'
  | 'trainings:read'
  | 'trainings:write'
  | 'uploads:write';
